// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// RouteableModule is an autogenerated mock type for the RouteableModule type
type RouteableModule struct {
	mock.Mock
}

// ApplyRoute provides a mock function with given fields: _a0
func (_m *RouteableModule) ApplyRoute(_a0 *echo.Echo) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewRouteableModule interface {
	mock.TestingT
	Cleanup(func())
}

// NewRouteableModule creates a new instance of RouteableModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRouteableModule(t mockConstructorTestingTNewRouteableModule) *RouteableModule {
	mock := &RouteableModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
